"""
The script computes the distance between the midpoints of two spinal levels (by default C2 and C8) along the spinal
cord centerline, with the midpoints defined as the center of mass of the rootlets of each level. The PMJ is not needed.

This is the same definition of the rootlets midpoints as used by `sct_register_to_template -lrootlet`
(`sct_labels.cubic_to_point`). Compare with the `distance_from_image_top_midpoint` column generated by
inter-rater_variability/02a_rootlets_to_spinal_levels.py (without -pmj), which defines the midpoints based on the
intersection of the rootlets and the spinal cord segmentation.

The script does the following:
    - compute the center of mass of each rootlets level using `sct_labels.cubic_to_point`
    - fit the spinal cord centerline from the spinal cord segmentation (same as in 02a_rootlets_to_spinal_levels.py
    without -pmj)
    - project the center of mass of each level on the centerline based on its slice and compute the distance between
    the first and the last level along the centerline

NOTE: `sct_labels.cubic_to_point` rounds the center of mass to the nearest voxel, so the midpoints are slice-wise
(i.e., precision of one slice).

The script requires the SCT conda environment to be activated:
    source ${SCT_DIR}/python/etc/profile.d/conda.sh
    conda activate venv_sct

Example:
    python 01b_compute_midpoints_distance_com.py -i sub-001_T2w_label-rootletseg.nii.gz -s sub-001_T2w_label-SC_seg.nii.gz

OR, the script can be run using a wrapper script 01_run_batch_rootlets_spinal_levels.sh

Authors: Jan Valosek
"""

import os
import argparse
import numpy as np
import pandas as pd

from spinalcordtoolbox.image import Image
from spinalcordtoolbox import labels as sct_labels
from spinalcordtoolbox.centerline.core import ParamCenterline, get_centerline

FIRST_LEVEL = 2
LAST_LEVEL = 8


def get_parser():
    """
    Function to parse command line arguments.
    :return: command line arguments
    """
    parser = argparse.ArgumentParser(
        description='Compute the distance between the midpoints of two spinal levels (default: C2 and C8) along the '
                    'spinal cord centerline, with the midpoints defined as the center of mass of the rootlets of each '
                    'level. The PMJ is not needed.',
        prog=os.path.basename(__file__).strip('.py'))
    parser.add_argument('-i', required=True, type=str,
                        help='Path to the rootlets segmentation (*_label-rootletseg.nii.gz) with one value per level.')
    parser.add_argument('-s', required=True, type=str, help='Path to the spinal cord segmentation.')
    parser.add_argument('-first', type=int, default=FIRST_LEVEL,
                        help=f'First (superior) spinal level. Default: {FIRST_LEVEL}.')
    parser.add_argument('-last', type=int, default=LAST_LEVEL,
                        help=f'Last (inferior) spinal level. Default: {LAST_LEVEL}.')
    parser.add_argument('-o', required=False, type=str,
                        help='Path to the output CSV file. Default: <input>_midpoints_distance_com.csv')
    return parser


def get_center_of_mass_slices(im_rootlets):
    """
    Get the slice of the center of mass of each rootlets level.
    :param im_rootlets: Image object of the rootlets segmentation in RPI orientation
    :return: dict: {level: slice of the center of mass}
    """
    im_com = sct_labels.cubic_to_point(im_rootlets)
    return {int(round(coord.value)): int(coord.z) for coord in im_com.getNonZeroCoordinates()}


def get_centerline_length(im_seg):
    """
    Fit the spinal cord centerline and compute the cumulative length (in mm) along it.
    Uses the same centerline as inter-rater_variability/02a_rootlets_to_spinal_levels.py without the -pmj flag.
    :param im_seg: Image object of the spinal cord segmentation in RPI orientation
    :return: arr_z: z slice index of each centerline point
    :return: arr_length: cumulative length (in mm) along the centerline at each centerline point
    """
    _, arr_ctl, _, _ = get_centerline(im_seg, ParamCenterline(algo_fitting='bspline', minmax=False), verbose=0)
    px, py, pz = im_seg.dim[4:7]
    # Distance between consecutive centerline points in mm
    steps = np.sqrt((np.diff(arr_ctl[0]) * px) ** 2 +
                    (np.diff(arr_ctl[1]) * py) ** 2 +
                    (np.diff(arr_ctl[2]) * pz) ** 2)
    arr_length = np.concatenate(([0], np.cumsum(steps)))

    return arr_ctl[2], arr_length


def main():
    parser = get_parser()
    args = parser.parse_args()

    fname_rootlets = args.i
    fname_out = args.o if args.o else fname_rootlets.replace('.nii.gz', '_midpoints_distance_com.csv')

    # Load input images using the SCT Image class
    im_rootlets = Image(fname_rootlets).change_orientation('RPI')
    im_seg = Image(args.s).change_orientation('RPI')

    com_slices = get_center_of_mass_slices(im_rootlets)
    arr_z, arr_length = get_centerline_length(im_seg)

    midpoints = dict()
    for level in [args.first, args.last]:
        if level not in com_slices:
            print(f'WARNING: Spinal level {level} not found in {fname_rootlets}; the distance will be NaN.')
            midpoints[level] = np.nan
        else:
            midpoints[level] = np.interp(com_slices[level], arr_z, arr_length)

    df = pd.DataFrame([{
        'fname': os.path.basename(fname_rootlets),
        'method': 'center_of_mass',
        'first_level': args.first,
        'last_level': args.last,
        'first_level_midpoint_slice': com_slices.get(args.first, np.nan),
        'last_level_midpoint_slice': com_slices.get(args.last, np.nan),
        'midpoints_distance_mm': abs(midpoints[args.last] - midpoints[args.first]),
    }])
    df.to_csv(fname_out, index=False)
    print(f'Distance between the midpoints (center of mass) of levels {args.first} and {args.last}: '
          f'{df["midpoints_distance_mm"].iloc[0]:.2f} mm')
    print(f'CSV file saved in {fname_out}.')


if __name__ == '__main__':
    main()
