"""
This script computes the distance between the C2 and C8 spinal level midpoints for each subject.

The distance is computed as C8 midpoint distance from the PMJ minus C2 midpoint distance from the PMJ).

Output:
- CSV file with the distance between the C2 and C8 midpoints for each subject (one row per subject)
- Figure with the distance between the C2 and C8 midpoints for each subject (subjects on x-axis, distance on y-axis)

The script was inspired by script '03a_generate_figure_inter_rater_variablity-PMJ_COV.py':
https://github.com/ivadomed/model-spinal-rootlets/blob/main/inter-rater_variability/03a_generate_figure_inter_rater_variablity-PMJ_COV.py
"""

import os
import glob
import argparse

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


FONT_SIZE = 14

# Levels whose midpoints are used for the distance computation: C2 and C8
FIRST_LEVEL = 2
LAST_LEVEL = 8

# participants.tsv with the subject sex
PARTICIPANTS_TSV = os.path.expanduser('~/data/data.neuro.polymtl.ca/data-multi-subject/participants.tsv')

# Female and male colors and markers
SEX_STYLE = {'F': {'color': '#2a78d6', 'marker': 'o', 'label': 'Female'},
             'M': {'color': '#eb6834', 'marker': 's', 'label': 'Male'}}


def get_parser():
    """
    Function to parse command line arguments.
    :return: command line arguments
    """
    parser = argparse.ArgumentParser(description='Compute the distance between the C2 and C8 spinal level midpoints '
                                                 'for each subject, save it to a CSV file and plot it.',
                                     prog=os.path.basename(__file__).strip('.py'))
    parser.add_argument('-i',
                        required=True,
                        type=str,
                        help='Path to the results (or data_processed) folder with CSV files for individual '
                             'subjects and spinal level estimation generated by the '
                             'inter-rater_variability/02a_rootlets_to_spinal_levels.py script. The output CSV files '
                             'and figure are saved to the current working directory.')
    parser.add_argument('-participants', default=PARTICIPANTS_TSV,
                        help=f'participants.tsv file with the subject sex (used to color the points). '
                             f'Default: {PARTICIPANTS_TSV}')
    return parser


def compute_midpoints_distance(df, first_level=FIRST_LEVEL, last_level=LAST_LEVEL):
    """
    Compute the distance between the midpoints of `first_level` and `last_level` for each subject as
    `distance_from_pmj_midpoint` of `last_level` minus `distance_from_pmj_midpoint` of `first_level`.
    :param df: dataframe with per-level distances from PMJ
    :return: dataframe with one row per subject
    """
    df_pivot = df.pivot_table(index='subject', columns='spinal_level', values='distance_from_pmj_midpoint')

    rows = []
    for subject, row in df_pivot.iterrows():
        midpoint_first = row.get(first_level, np.nan)
        midpoint_last = row.get(last_level, np.nan)
        missing = [level for level, midpoint in [(first_level, midpoint_first), (last_level, midpoint_last)]
                   if np.isnan(midpoint)]
        if missing:
            print(f"WARNING: {subject} is missing level(s) {','.join(map(str, missing))}; "
                  f"the distance between the midpoints will be NaN.")

        rows.append({
            'subject': subject,
            'first_level': first_level,
            'last_level': last_level,
            'distance_from_pmj_midpoint_first_level_mm': midpoint_first,
            'distance_from_pmj_midpoint_last_level_mm': midpoint_last,
            'midpoints_distance_mm': midpoint_last - midpoint_first
        })

    return pd.DataFrame(rows)


def generate_midpoints_distance_figure(df_midpoints, dir_path, first_level=FIRST_LEVEL, last_level=LAST_LEVEL):
    """
    Generate a figure with subjects on the x-axis and the distance between the `first_level` and `last_level`
    midpoints on the y-axis (one point per subject).
    :param df_midpoints: dataframe returned by compute_midpoints_distance() with an added 'sex' column
    :param dir_path: path to the output folder where the figure will be saved
    """
    df_plot = df_midpoints.sort_values('subject').reset_index(drop=True)

    # Fixed figure size; subjects are shown as numbers (no subject names) so the figure stays compact
    fig, ax = plt.subplots(figsize=(8, 5))
    # Points colored by sex; subjects without sex information in gray
    x = np.arange(1, len(df_plot) + 1)
    y = (df_plot['midpoints_distance_mm']).to_numpy() / 10  # convert mm to cm for plotting
    for sex, style in SEX_STYLE.items():
        mask = (df_plot['sex'] == sex).to_numpy()
        ax.scatter(x[mask], y[mask], color=style['color'], marker=style['marker'], s=30, zorder=3,
                   label=f"{style['label']} (n = {mask.sum()})")
    mask = (~df_plot['sex'].isin(list(SEX_STYLE))).to_numpy()
    if mask.any():
        ax.scatter(x[mask], y[mask], color='gray', marker='x', s=30, zorder=3,
                   label=f'Sex unknown (n = {mask.sum()})')

    # Subjects (sorted alphabetically, i.e., grouped by site) as numbered x-axis positions
    ax.set_xlim(0.5, len(df_plot) + 0.5)
    ax.set_xlabel(f'Subject (n = {len(df_plot)})', fontsize=FONT_SIZE)
    ax.set_ylim(0, 12)

    ax.set_ylabel(f'Distance C{first_level}–C{last_level} midpoints [cm]', fontsize=FONT_SIZE)
    ax.tick_params(axis='y', labelsize=FONT_SIZE - 2)
    ax.tick_params(axis='x', labelsize=FONT_SIZE - 2)
    ax.grid(axis='y', alpha=0.2)
    ax.set_axisbelow(True)
    ax.spines['right'].set_visible(False)
    ax.spines['top'].set_visible(False)
    # Legend above the plot so it does not overlap the points
    ax.legend(loc='lower right', bbox_to_anchor=(1, 1), ncol=3, frameon=False, fontsize=FONT_SIZE - 4,
              handletextpad=0.3, columnspacing=1)

    plt.tight_layout()

    fname_figure = os.path.join(dir_path, f'figure_spinal_levels_midpoints_distance_{first_level}-{last_level}.png')
    fig.savefig(fname_figure, dpi=300)
    print(f'Figure saved to {fname_figure}')
    plt.show()


def main():
    parser = get_parser()
    args = parser.parse_args()
    dir_path = os.path.abspath(args.i)
    # Outputs (CSV files and figure) are saved to the current working directory
    out_dir = os.getcwd()

    # Get all the CSV files generated by the 02a_rootlets_to_spinal_levels.py script
    csv_files = glob.glob(os.path.join(dir_path, '**', '*pmj_distance*.csv'), recursive=True)
    if not csv_files:
        raise FileNotFoundError(f'No *pmj_distance*.csv files found in {dir_path}. Check the -i path.')

    # Initialize an empty list to store the parsed data
    parsed_data = []

    # Loop across CSV files and aggregate the results into pandas dataframe
    for csv_file in csv_files:
        df_file = pd.read_csv(csv_file)
        parsed_data.append(df_file)

    # Combine list of dataframes into one dataframe
    df = pd.concat(parsed_data)

    # Extract subjectID from the fname and add it as a column
    df['subject'] = df['fname'].apply(lambda x: x.split('_')[0])

    # Extract spinal levels (cervical '2-8')
    df = df[df['spinal_level'].isin([2, 3, 4, 5, 6, 7, 8])]

    # sort df by subject and spinal level
    df = df.sort_values(by=['subject', 'spinal_level'])

    # Save dataframe with all subjects to CSV file
    fname_out = os.path.join(out_dir, 'spinal_levels_spine-generic.csv')
    df.to_csv(fname_out, index=False)
    print(f'CSV file saved in {fname_out}.')

    # Compute the distance between the C2 and C8 midpoints (one value per subject)
    df_midpoints = compute_midpoints_distance(df, FIRST_LEVEL, LAST_LEVEL)
    fname_midpoints = os.path.join(out_dir,
                                   f'spinal_levels_midpoints_distance_{FIRST_LEVEL}-{LAST_LEVEL}_spine-generic.csv')
    df_midpoints.to_csv(fname_midpoints, index=False)
    print(f'Distance between the midpoints of levels {FIRST_LEVEL} and {LAST_LEVEL} saved in {fname_midpoints}.')
    print(df_midpoints[['subject', 'midpoints_distance_mm']].describe())

    # Add the subject sex (used only to color the points in the figure)
    df_participants = pd.read_csv(args.participants, sep='\t')
    df_midpoints = df_midpoints.merge(df_participants[['participant_id', 'sex']], how='left',
                                      left_on='subject', right_on='participant_id')

    # Plot the distance between the C2 and C8 midpoints per subject
    generate_midpoints_distance_figure(df_midpoints, out_dir, FIRST_LEVEL, LAST_LEVEL)


if __name__ == '__main__':
    main()