# This script computes the total height spanning spinal levels 2 to 8 (C2-C8) for each subject,
# saves it to a CSV file and plots it as a figure (subjects on x-axis, total height on y-axis).
# It also saves a CSV file with the per-level distances from the PMJ for all subjects.

# The script was inspired by script '03a_generate_figure_inter_rater_variablity-PMJ_COV.py':
# https://github.com/ivadomed/model-spinal-rootlets/blob/main/inter-rater_variability/03a_generate_figure_inter_rater_variablity-PMJ_COV.py

import os
import glob
import argparse

import pandas as pd
import matplotlib.pyplot as plt

# Initialize dictionaries
LEVEL_TYPE_COLOR = {'rootlets': 'red', 'vertebrae': 'green'}
FONT_SIZE = 14

# Range of levels for the total height computation
FIRST_LEVEL = 2
LAST_LEVEL = 8


def get_parser():
    """
    Function to parse command line arguments.
    :return: command line arguments
    """
    parser = argparse.ArgumentParser(description='Compute the total height from spinal level 2 to level 8 for each subject, '
                                                 'save it to a CSV file and plot it.', prog=os.path.basename(__file__).strip('.py'))
    parser.add_argument('-i', required=True, type=str, help='Path to the data_processed folder with CSV '
                                                            'files for individual subjects and spinal/vertebral level estimation generated by the '
                                                            'inter-rater_variability/02a_rootlets_to_spinal_levels.py script. '
                                                            'The figure will be saved to the same folder.')
    parser.add_argument('-participants', required=False, type=str, help='Path to the participants.tsv file.')
    return parser


def compute_total_height(df, first_level=FIRST_LEVEL, last_level=LAST_LEVEL):
    """
    Compute the total craniocaudal height spanning from the rostral edge of `first_level` to the caudal edge of
    `last_level` (i.e., one value per subject, not per level).
    Computed as the span (max distance from PMJ - min distance from PMJ), so any gaps or overlaps between
    adjacent levels are handled correctly. The sum of per-level heights is also reported for comparison.
    :param df: dataframe with per-level distances from PMJ
    :return: dataframe with one row per subject and level type
    """
    df_range = df[df['spinal_level'].between(first_level, last_level)]

    rows = []
    for (subject, level_type), grp in df_range.groupby(['subject', 'spinal_level_type']):
        levels_present = set(grp['spinal_level'])
        missing = sorted(set(range(first_level, last_level + 1)) - levels_present)

        # Use both start and end columns so the result does not depend on which one is rostral
        rostral = grp[['distance_from_pmj_start', 'distance_from_pmj_end']].min(axis=1).min()
        caudal = grp[['distance_from_pmj_start', 'distance_from_pmj_end']].max(axis=1).max()

        rows.append({
            'subject': subject,
            'spinal_level_type': level_type,
            'first_level': first_level,
            'last_level': last_level,
            'distance_from_pmj_rostral_mm': rostral,
            'distance_from_pmj_caudal_mm': caudal,
            'total_height_mm': caudal - rostral,
            'total_height_cm': (caudal - rostral) / 10.0,
            'sum_of_level_heights': grp['height'].sum(),
            'missing_levels': ','.join(map(str, missing)) if missing else '',
        })

    df_height = pd.DataFrame(rows)

    # Warn about subjects where the full range is not available (height would be underestimated)
    incomplete = df_height[df_height['missing_levels'] != '']
    for _, r in incomplete.iterrows():
        print(f"WARNING: {r['subject']} ({r['spinal_level_type']}) is missing level(s) {r['missing_levels']}; "
              f"total_height may be underestimated.")

    return df_height


def generate_height_figure(df_height, dir_path, first_level=FIRST_LEVEL, last_level=LAST_LEVEL):
    """
    Generate a figure with subjects on the x-axis and the total height from `first_level` to `last_level`
    on the y-axis (one point per subject).
    :param df_height: dataframe returned by compute_total_height()
    :param dir_path: path to the output folder where the figure will be saved
    """
    df_plot = df_height.sort_values('subject').reset_index(drop=True)
    x = range(1, len(df_plot) + 1)

    fig, ax = plt.subplots(figsize=(max(6, len(df_plot) * 0.6), 5))
    ax.scatter(x, df_plot['total_height_cm'], color=LEVEL_TYPE_COLOR['rootlets'], s=50, zorder=3)

    # Subject names as x-axis labels
    ax.set_xticks(list(x))
    ax.set_xticklabels(df_plot['subject'], rotation=45, ha='right')
    ax.set_xlim(0.5, len(df_plot) + 0.5)
    ax.set_ylim(5, 12)

    ax.set_ylabel(f'Height C{first_level}–C{last_level} [cm]', fontsize=FONT_SIZE)
    ax.tick_params(axis='y', labelsize=FONT_SIZE - 2)
    ax.tick_params(axis='x', labelsize=FONT_SIZE - 2)
    ax.grid(axis='y', alpha=0.2)
    ax.set_axisbelow(True)
    ax.spines['right'].set_visible(False)
    ax.spines['top'].set_visible(False)

    plt.tight_layout()

    fname_figure = os.path.join(dir_path, f'figure_spinal_levels_height_{first_level}-{last_level}.png')
    fig.savefig(fname_figure, dpi=300)
    print(f'Figure saved to {fname_figure}')
    plt.show()


def main():
    parser = get_parser()
    args = parser.parse_args()
    dir_path = os.path.abspath(args.i)

    # Get all the CSV files generated by the 02a_rootlets_to_spinal_levels.py or discs_to_vertebral_levels.py scripts
    csv_files = glob.glob(os.path.join(dir_path, '**', '*pmj_distance*.csv'), recursive=True)

    # Initialize an empty list to store the parsed data
    parsed_data = []

    # Loop across CSV files and aggregate the results into pandas dataframe
    for csv_file in csv_files:
        df_file = pd.read_csv(csv_file)
        parsed_data.append(df_file)

    # Combine list of dataframes into one dataframe
    df = pd.concat(parsed_data)

    # Extract rootlets or vertebrae level type from the fname and add it as a column
    df['spinal_level_type'] = df['fname'].apply(
        lambda x: 'rootlets' if 'rootlets' in x else 'vertebrae'
    )

    # Extract subjectID from the fname and add it as a column
    df['subject'] = df['fname'].apply(lambda x: x.split('_')[0])

    # Extract spinal levels (cervical '2-8', thoracic '9')
    df = df[((df['spinal_level_type'] == 'rootlets') & (df['spinal_level'].isin([2, 3, 4, 5, 6, 7, 8, 9])))]

    # sort df by subject, spinal level type and spinal level
    df = df.sort_values(by=['subject', 'spinal_level_type', 'spinal_level'])

    # Save dataframe with all subjects to CSV file
    fname_out = os.path.join(dir_path, 'spinal_levels_spine-generic.csv')
    df.to_csv(fname_out, index=False)
    print(f'CSV file saved in {fname_out}.')

    # Compute total height from level 2 to level 8 (one value per subject)
    df_height = compute_total_height(df, FIRST_LEVEL, LAST_LEVEL)
    fname_height = os.path.join(dir_path, f'spinal_levels_height_{FIRST_LEVEL}-{LAST_LEVEL}_spine-generic.csv')
    df_height.to_csv(fname_height, index=False)
    print(f'Total height (levels {FIRST_LEVEL}-{LAST_LEVEL}) saved in {fname_height}.')
    print(df_height[['subject', 'total_height_cm']].describe())

    # Plot total height per subject
    generate_height_figure(df_height, dir_path, FIRST_LEVEL, LAST_LEVEL)


if __name__ == '__main__':
    main()