#
# This script computes the distance between the C2 and C8 spinal level midpoints for each subject (C8 midpoint distance
# from the PMJ minus C2 midpoint distance from the PMJ), saves it to a CSV file and plots it as a figure (subjects on
# x-axis, distance on y-axis).
# It also saves a CSV file with the per-level distances from the PMJ for all subjects.

# The script was inspired by script '03a_generate_figure_inter_rater_variablity-PMJ_COV.py':
# https://github.com/ivadomed/model-spinal-rootlets/blob/main/inter-rater_variability/03a_generate_figure_inter_rater_variablity-PMJ_COV.py

import os
import glob
import argparse

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


FONT_SIZE = 14

# Levels whose midpoints are used for the distance computation: C2 and C8
FIRST_LEVEL = 2
LAST_LEVEL = 8


def get_parser():
    """
    Function to parse command line arguments.
    :return: command line arguments
    """
    parser = argparse.ArgumentParser(description='Compute the distance between the C2 and C8 spinal level midpoints '
                                                 'for each subject, save it to a CSV file and plot it.',
                                     prog=os.path.basename(__file__).strip('.py'))
    parser.add_argument('-i',
                        required=True,
                        type=str,
                        help='Path to the data_processed folder with CSV files for individual subjects and spinal '
                             'level estimation generated by the inter-rater_variability/02a_rootlets_to_spinal_levels.py '
                             'script. The figure will be saved to the same folder.')
    return parser


def compute_midpoints_distance(df, first_level=FIRST_LEVEL, last_level=LAST_LEVEL):
    """
    Compute the distance between the midpoints of `first_level` and `last_level` for each subject as
    `distance_from_pmj_midpoint` of `last_level` minus `distance_from_pmj_midpoint` of `first_level`.
    :param df: dataframe with per-level distances from PMJ
    :return: dataframe with one row per subject
    """
    df_pivot = df.pivot_table(index='subject', columns='spinal_level', values='distance_from_pmj_midpoint')

    rows = []
    for subject, row in df_pivot.iterrows():
        midpoint_first = row.get(first_level, np.nan)
        midpoint_last = row.get(last_level, np.nan)
        missing = [level for level, midpoint in [(first_level, midpoint_first), (last_level, midpoint_last)]
                   if np.isnan(midpoint)]
        if missing:
            print(f"WARNING: {subject} is missing level(s) {','.join(map(str, missing))}; "
                  f"the distance between the midpoints will be NaN.")

        rows.append({
            'subject': subject,
            'first_level': first_level,
            'last_level': last_level,
            'distance_from_pmj_midpoint_first_level_mm': midpoint_first,
            'distance_from_pmj_midpoint_last_level_mm': midpoint_last,
            'midpoints_distance_mm': midpoint_last - midpoint_first
        })

    return pd.DataFrame(rows)


def generate_midpoints_distance_figure(df_midpoints, dir_path, first_level=FIRST_LEVEL, last_level=LAST_LEVEL):
    """
    Generate a figure with subjects on the x-axis and the distance between the `first_level` and `last_level`
    midpoints on the y-axis (one point per subject).
    :param df_midpoints: dataframe returned by compute_midpoints_distance()
    :param dir_path: path to the output folder where the figure will be saved
    """
    df_plot = df_midpoints.sort_values('subject').reset_index(drop=True)
    x = range(1, len(df_plot) + 1)

    fig, ax = plt.subplots(figsize=(max(6, len(df_plot) * 0.6), 5))
    # Convert mm to cm for plotting
    ax.scatter(x, df_plot['midpoints_distance_mm'] / 10, color='red', s=50, zorder=3)

    # Subject names as x-axis labels
    ax.set_xticks(list(x))
    ax.set_xticklabels(df_plot['subject'], rotation=45, ha='right')
    ax.set_xlim(0.5, len(df_plot) + 0.5)
    ax.set_ylim(0, 12)

    ax.set_ylabel(f'Distance C{first_level}–C{last_level} midpoints [cm]', fontsize=FONT_SIZE)
    ax.tick_params(axis='y', labelsize=FONT_SIZE - 2)
    ax.tick_params(axis='x', labelsize=FONT_SIZE - 2)
    ax.grid(axis='y', alpha=0.2)
    ax.set_axisbelow(True)
    ax.spines['right'].set_visible(False)
    ax.spines['top'].set_visible(False)

    plt.tight_layout()

    fname_figure = os.path.join(dir_path, f'figure_spinal_levels_midpoints_distance_{first_level}-{last_level}.png')
    fig.savefig(fname_figure, dpi=300)
    print(f'Figure saved to {fname_figure}')
    plt.show()


def main():
    parser = get_parser()
    args = parser.parse_args()
    dir_path = os.path.abspath(args.i)

    # Get all the CSV files generated by the 02a_rootlets_to_spinal_levels.py script
    csv_files = glob.glob(os.path.join(dir_path, '**', '*pmj_distance*.csv'), recursive=True)

    # Initialize an empty list to store the parsed data
    parsed_data = []

    # Loop across CSV files and aggregate the results into pandas dataframe
    for csv_file in csv_files:
        df_file = pd.read_csv(csv_file)
        parsed_data.append(df_file)

    # Combine list of dataframes into one dataframe
    df = pd.concat(parsed_data)

    # Extract subjectID from the fname and add it as a column
    df['subject'] = df['fname'].apply(lambda x: x.split('_')[0])

    # Extract spinal levels (cervical '2-8')
    df = df[df['spinal_level'].isin([2, 3, 4, 5, 6, 7, 8])]

    # sort df by subject and spinal level
    df = df.sort_values(by=['subject', 'spinal_level'])

    # Save dataframe with all subjects to CSV file
    fname_out = os.path.join(dir_path, 'spinal_levels_spine-generic.csv')
    df.to_csv(fname_out, index=False)
    print(f'CSV file saved in {fname_out}.')

    # Compute the distance between the C2 and C8 midpoints (one value per subject)
    df_midpoints = compute_midpoints_distance(df, FIRST_LEVEL, LAST_LEVEL)
    fname_midpoints = os.path.join(dir_path,
                                   f'spinal_levels_midpoints_distance_{FIRST_LEVEL}-{LAST_LEVEL}_spine-generic.csv')
    df_midpoints.to_csv(fname_midpoints, index=False)
    print(f'Distance between the midpoints of levels {FIRST_LEVEL} and {LAST_LEVEL} saved in {fname_midpoints}.')
    print(df_midpoints[['subject', 'midpoints_distance_mm']].describe())

    # Plot the distance between the C2 and C8 midpoints per subject
    generate_midpoints_distance_figure(df_midpoints, dir_path, FIRST_LEVEL, LAST_LEVEL)


if __name__ == '__main__':
    main()