"""
This script plots the correlation between the distance of the C2 and C8 spinal level midpoints and subject height.

Input:
- CSV file with the C2-C8 midpoints distance per subject generated by 02_compute_cervical_midpoints_distance.py
  (spinal_levels_midpoints_distance_2-8_spine-generic.csv)
- participants.tsv file with the subject height (in cm)
  (default: ~/data/data.neuro.polymtl.ca/data-multi-subject/participants.tsv)

Output (saved to the same folder as the input CSV):
    - figure_correlation_cervical_midpoints_distance_2-8_height.png: scatter plot with a linear fit (visual guide), the
      Spearman correlation coefficient and the Shapiro-Wilk normality test p-values

Spearman correlation is used because the distance is not normally distributed (Shapiro-Wilk test) and the sample is
small, so a single subject can strongly influence the Pearson correlation.

Example:
    python 05_correlation_cervical_length_height.py -i spinal_levels_midpoints_distance_2-8_spine-generic.csv

Author: Jan Valosek
"""

import os
import argparse
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

FONT_SIZE = 14

PARTICIPANTS_TSV = os.path.expanduser('~/data/data.neuro.polymtl.ca/data-multi-subject/participants.tsv')

# Female and male colors and markers
SEX_STYLE = {'F': {'color': '#2a78d6', 'marker': 'o', 'label': 'Female'},
             'M': {'color': '#eb6834', 'marker': 's', 'label': 'Male'}}


def spearman_ci(rho, n, alpha=0.05):
    """
    Confidence interval of the Spearman correlation coefficient using the Fisher z-transformation with the
    Bonett & Wright (2000) standard error, sqrt(1.06 / (n - 3)).
    """
    z = np.arctanh(rho)
    se = np.sqrt(1.06 / (n - 3))
    z_crit = stats.norm.ppf(1 - alpha / 2)
    return np.tanh(z - z_crit * se), np.tanh(z + z_crit * se)


def linear_fit_ci_band(x, y, x_fit, alpha=0.05):
    """
    Linear fit and the confidence band of the fitted mean (ordinary least squares).
    :return: y_fit, lower bound, upper bound evaluated at x_fit
    """
    n = len(x)
    slope, intercept = np.polyfit(x, y, 1)
    y_fit = slope * x_fit + intercept
    residuals = y - (slope * x + intercept)
    s = np.sqrt(np.sum(residuals ** 2) / (n - 2))   # residual standard error
    se_fit = s * np.sqrt(1 / n + (x_fit - x.mean()) ** 2 / np.sum((x - x.mean()) ** 2))
    t_crit = stats.t.ppf(1 - alpha / 2, n - 2)
    return y_fit, y_fit - t_crit * se_fit, y_fit + t_crit * se_fit


def main():
    parser = argparse.ArgumentParser(description='Plot the correlation between the C2-C8 midpoints distance and '
                                                 'subject height.')
    parser.add_argument('-i', required=True,
                        help='CSV file with the C2-C8 midpoints distance per subject generated by '
                             '02_compute_cervical_midpoints_distance.py.')
    parser.add_argument('-participants', default=PARTICIPANTS_TSV,
                        help=f'participants.tsv file with the subject height. Default: {PARTICIPANTS_TSV}')
    args = parser.parse_args()

    # Load the distances and the heights, and merge them by subject
    df = pd.read_csv(args.i)
    df_participants = pd.read_csv(args.participants, sep='\t')
    df = df.merge(df_participants[['participant_id', 'height', 'sex']], left_on='subject', right_on='participant_id')

    # Keep only subjects with both the distance and the height available
    df = df.dropna(subset=['midpoints_distance_mm', 'height'])

    height = df['height']                           # in cm
    distance = df['midpoints_distance_mm'] / 10     # convert mm to cm

    # Normality test (Shapiro-Wilk); p < 0.05 means the data are not normally distributed
    p_norm_height = stats.shapiro(height).pvalue
    print(f'Shapiro-Wilk normality test: height p = {p_norm_height:.3f}')

    # Spearman correlation (rank-based, does not assume normality and is robust to outliers)
    rho, p = stats.spearmanr(height, distance)
    print(f'n = {len(df)}, Spearman rho = {rho:.2f}, p = {p:.3f}')

    # 95% confidence interval of the Spearman correlation coefficient
    rho_lo, rho_hi = spearman_ci(rho, len(df))
    print(f'Spearman rho 95% CI = [{rho_lo:.2f}, {rho_hi:.2f}]')

    # Scatter plot, colored by sex
    fig, ax = plt.subplots(figsize=(6, 5))
    for sex, style in SEX_STYLE.items():
        mask = df['sex'] == sex
        ax.scatter(height[mask], distance[mask], color=style['color'], marker=style['marker'], s=50, zorder=3,
                   label=f"{style['label']} (n = {mask.sum()})")

    # Linear fit across all subjects (only as a visual guide) with its 95% confidence band
    x_fit = np.linspace(height.min(), height.max(), 100)
    y_fit, y_lo, y_hi = linear_fit_ci_band(height.to_numpy(), distance.to_numpy(), x_fit)
    ax.fill_between(x_fit, y_lo, y_hi, color='gray', alpha=0.2, linewidth=0, zorder=1,
                    label='Linear fit, 95% CI')
    ax.plot(x_fit, y_fit, color='black', linewidth=2, zorder=2)

    # Spearman correlation and normality test in the upper left corner
    ax.text(0.03, 0.97,
            f'n = {len(df)}\nSpearman ρ = {rho:.2f} [95% CI {rho_lo:.2f}, {rho_hi:.2f}], p = {p:.3f}',
            transform=ax.transAxes, fontsize=FONT_SIZE - 4, va='top')

    ax.set_xlabel('Height [cm]', fontsize=FONT_SIZE)
    ax.set_ylabel('Distance C2–C8 midpoints [cm]', fontsize=FONT_SIZE)
    ax.tick_params(axis='both', labelsize=FONT_SIZE - 2)
    ax.grid(alpha=0.2)
    ax.set_axisbelow(True)
    ax.spines['right'].set_visible(False)
    ax.spines['top'].set_visible(False)
    # Add headroom above the data for the correlation text
    y_min, y_max = ax.get_ylim()
    ax.set_ylim(y_min, y_max + 0.2 * (y_max - y_min))
    # Legend above the plot so it does not overlap the points or the correlation text
    ax.legend(loc='lower right', bbox_to_anchor=(1, 1), ncol=3, frameon=False, fontsize=FONT_SIZE - 5,
              handletextpad=0.3, columnspacing=1)

    plt.tight_layout()

    fname_figure = os.path.join(os.path.dirname(os.path.abspath(args.i)),
                                'figure_correlation_cervical_midpoints_distance_2-8_height.png')
    fig.savefig(fname_figure, dpi=300)
    print(f'Figure saved to {fname_figure}')
    plt.show()


if __name__ == '__main__':
    main()
