"""
This script plots the correlation between a lumbar spinal level length and subject height.

Input:
- CSV file with the lumbar length per subject generated by 03_compute_lumbar_midpoints_distance.py
  (lumbar_midpoints_distance_L1-S1.csv) or 04_compute_lumbar_length_topL1_bottom_L5.py (lumbar_length_L1-L5.csv).
  The length is read from the column starting with 'midpoints_distance_' or 'length_'.
  (default: ~/results/lumbar_rootlets_Balgrist/spinal_level_segmentation_L1-S2/lumbar_midpoints_distance_L1-S1.csv)
- Excel file with the subject height ('Height (cm)' column in the 'Spinal level heights (mm)' sheet)
  (default: ~/results/lumbar_rootlets_Balgrist/spinal_level_segmentation_L1-S2/
  spinal_level_heights_top_L1-bottom_S2_with_chart.xlsx)

Output (saved to the same folder as the input CSV):
    - figure_correlation_<length>_height.png: scatter plot with a linear fit (visual guide) and the Spearman
      correlation coefficient

Spearman correlation is used for consistency with 05_correlation_cervical_length_height.py; it does not assume normality
and is robust to outliers, which matters for a small sample.

Example:
    python 06_correlation_lumbar_length_height.py
    python 06_correlation_lumbar_length_height.py -i lumbar_length_L1-L5.csv

Author: Jan Valosek
"""

import os
import argparse
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator
from scipy import stats

FONT_SIZE = 14

LENGTHS_CSV = os.path.expanduser('~/results/lumbar_rootlets_Balgrist/spinal_level_segmentation_L1-S2/'
                                 'lumbar_midpoints_distance_L1-S1.csv')
HEIGHTS_XLSX = os.path.expanduser('~/results/lumbar_rootlets_Balgrist/spinal_level_segmentation_L1-S2/'
                                  'spinal_level_heights_top_L1-bottom_S2_with_chart.xlsx')
HEIGHTS_SHEET = 'Spinal level heights (mm)'


# Female and male colors and markers
SEX_STYLE = {'F': {'color': '#2a78d6', 'marker': 'o', 'label': 'Female'},
             'M': {'color': '#eb6834', 'marker': 's', 'label': 'Male'}}


def spearman_ci(rho, n, alpha=0.05):
    """
    Confidence interval of the Spearman correlation coefficient using the Fisher z-transformation with the
    Bonett & Wright (2000) standard error, sqrt(1.06 / (n - 3)).
    """
    z = np.arctanh(rho)
    se = np.sqrt(1.06 / (n - 3))
    z_crit = stats.norm.ppf(1 - alpha / 2)
    return np.tanh(z - z_crit * se), np.tanh(z + z_crit * se)


def linear_fit_ci_band(x, y, x_fit, alpha=0.05):
    """
    Linear fit and the confidence band of the fitted mean (ordinary least squares).
    :return: y_fit, lower bound, upper bound evaluated at x_fit
    """
    n = len(x)
    slope, intercept = np.polyfit(x, y, 1)
    y_fit = slope * x_fit + intercept
    residuals = y - (slope * x + intercept)
    s = np.sqrt(np.sum(residuals ** 2) / (n - 2))   # residual standard error
    se_fit = s * np.sqrt(1 / n + (x_fit - x.mean()) ** 2 / np.sum((x - x.mean()) ** 2))
    t_crit = stats.t.ppf(1 - alpha / 2, n - 2)
    return y_fit, y_fit - t_crit * se_fit, y_fit + t_crit * se_fit


def main():
    parser = argparse.ArgumentParser(description='Plot the correlation between a lumbar length and subject height.')
    parser.add_argument('-i', default=LENGTHS_CSV,
                        help='CSV file with the lumbar length per subject generated by '
                             '03_compute_lumbar_midpoints_distance.py or 04_compute_lumbar_length_topL1_bottom_L5.py. '
                             f'Default: {LENGTHS_CSV}')
    parser.add_argument('-xlsx', default=HEIGHTS_XLSX,
                        help=f'Excel file with the subject height. Default: {HEIGHTS_XLSX}')
    args = parser.parse_args()

    # Load the lengths; the length column is e.g. 'midpoints_distance_L1-S1_mm' or 'length_L1-L5_mm'
    df = pd.read_csv(args.i)
    length_column = [c for c in df.columns if c.startswith(('midpoints_distance_', 'length_'))][0]
    print(f'Using length column: {length_column}')

    # Load the heights from the Excel file (only the subject rows; the sheet also contains a mean row and a chart)
    df_heights = pd.read_excel(args.xlsx, sheet_name=HEIGHTS_SHEET)
    df_heights = df_heights[df_heights['Participants'].astype(str).str.startswith('sub-')]

    # Merge by subject and keep only subjects with both the length and the height available
    df = df.merge(df_heights[['Participants', 'Height (cm)', 'sex']], left_on='subject', right_on='Participants')
    df = df.dropna(subset=[length_column, 'Height (cm)'])
    df['sex'] = df['sex'].str.upper()   # 'f'/'m' -> 'F'/'M'

    height = df['Height (cm)'].astype(float)        # in cm
    length = df[length_column] / 10                 # convert mm to cm

    # Normality test (Shapiro-Wilk); p < 0.05 means the data are not normally distributed
    p_norm_height = stats.shapiro(height).pvalue
    print(f'Shapiro-Wilk normality test: height p = {p_norm_height:.3f}')

    # Spearman correlation (rank-based, does not assume normality and is robust to outliers)
    rho, p = stats.spearmanr(height, length)
    print(f'n = {len(df)}, Spearman rho = {rho:.2f}, p = {p:.3f}')

    # 95% confidence interval of the Spearman correlation coefficient
    rho_lo, rho_hi = spearman_ci(rho, len(df))
    print(f'Spearman rho 95% CI = [{rho_lo:.2f}, {rho_hi:.2f}]')

    # Scatter plot, colored by sex
    fig, ax = plt.subplots(figsize=(6, 5))
    for sex, style in SEX_STYLE.items():
        mask = df['sex'] == sex
        ax.scatter(height[mask], length[mask], color=style['color'], marker=style['marker'], s=50, zorder=3,
                   label=f"{style['label']} (n = {mask.sum()})")

    # Linear fit across all subjects (only as a visual guide) with its 95% confidence band
    x_fit = np.linspace(height.min(), height.max(), 100)
    y_fit, y_lo, y_hi = linear_fit_ci_band(height.to_numpy(), length.to_numpy(), x_fit)
    ax.fill_between(x_fit, y_lo, y_hi, color='gray', alpha=0.2, linewidth=0, zorder=1,
                    label='Linear fit, 95% CI')
    ax.plot(x_fit, y_fit, color='black', linewidth=2, zorder=2)

    # Spearman correlation in the upper left corner
    ax.text(0.03, 0.97,
            f'n = {len(df)}\nSpearman ρ = {rho:.2f} [95% CI {rho_lo:.2f}, {rho_hi:.2f}], p = {p:.3f}',
            transform=ax.transAxes, fontsize=FONT_SIZE - 4, va='top')

    # Y-axis label from the length column, e.g. 'midpoints_distance_L1-S1_mm' -> 'Distance L1–S1 midpoints [cm]'
    levels = length_column.split('_')[-2].replace('-', '–')
    ylabel = f'Distance {levels} midpoints [cm]' if length_column.startswith('midpoints_distance_') \
        else f'Length {levels} [cm]'

    ax.set_xlabel('Height [cm]', fontsize=FONT_SIZE)
    ax.xaxis.set_major_locator(MaxNLocator(integer=True, steps=[1, 2, 5, 10]))  # integer ticks for height
    ax.set_ylabel(ylabel, fontsize=FONT_SIZE)
    ax.tick_params(axis='both', labelsize=FONT_SIZE - 2)
    ax.grid(alpha=0.2)
    ax.set_axisbelow(True)
    ax.spines['right'].set_visible(False)
    ax.spines['top'].set_visible(False)
    # Add headroom above the data for the correlation text
    y_min, y_max = ax.get_ylim()
    ax.set_ylim(y_min, y_max + 0.2 * (y_max - y_min))
    # Legend above the plot so it does not overlap the points or the correlation text
    ax.legend(loc='lower right', bbox_to_anchor=(1, 1), ncol=3, frameon=False, fontsize=FONT_SIZE - 5,
              handletextpad=0.3, columnspacing=1)

    plt.tight_layout()

    fname_figure = os.path.join(os.path.dirname(os.path.abspath(args.i)),
                                f'figure_correlation_{length_column.removesuffix("_mm")}_height.png')
    fig.savefig(fname_figure, dpi=300)
    print(f'Figure saved to {fname_figure}')
    plt.show()


if __name__ == '__main__':
    main()
